media:
  input: src/assets
  output: ../../assets
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, pubDate ]
    fields:
      - name: pubDate
        label: Publish Date
        type: date
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: body
        label: Body
        type: rich-text